[package]
name = "catch"
version = "1.2.1"
edition = "2024"

[dependencies]
actix-multipart = "0.7"
actix-web = "4"
awc = { version = "3", features = ["rustls"] }
base64 = "0.22"
chrono = "0.4"
env_logger = "0.11.8"
futures-util = "0.3"
ion = { git = "https://github.com/alshdavid/ion.git", version = "0.2.0" }
log = "0.4.29"
maud = { version = "0.27.0", features = ["actix-web"] }
mime_guess = "2"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.149"
uuid = { version = "1", features = ["v4"] }
xshell = "0.2"
